services:
  backend:
    build: ./backend
    container_name: todolist-backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=mqzesh
      - DB_PASSWORD=mqzesh
      - DB_NAME=todolist_db
      - JWT_SECRET=d86%^u$d^G49KC^h*E1%oVRc6
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: todolist-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: todolist-database
    restart: always
    environment:
      - POSTGRES_USER=mqzesh
      - POSTGRES_PASSWORD=mqzesh
      - POSTGRES_DB=todolist_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d   # ✅ SQL dosyaları buradan çalışacak

volumes:
  postgres-data: